### ISSUE TITLE
Enhance Project with Required React Components

### ISSUE THREAD

**Issue by jdregalario-stacktrek** [Kvngxel/cloneSite#1]
Currently, your clone app is lacking the essential React components needed to fulfill the activity requirements. As per the guidelines, we are expected to have a minimum of 5 React components integrated into the project. Please note that `data.jsx` file is a separate requirement for the activity, so it is not part of the five components.

**_Action Item:_**

- [ ]  Create one more component in your clone app.

**Comment by jdregalario-stacktrek** [comment]
**Additional Information:**

Please feel free to comment if you have any suggestions or thoughts on the proposed solution. Maintaining a consistent code formatting style will benefit the entire team and enhance our codebase's overall quality.

**Comment by jdregalario-stacktrek** [comment]
@Kvngxel

**Comment by Kvngxel** [comment]
Issue has been solved, I added the 5th component and pushed
